baseURL = 'https://DatamatikerTeam6.github.io/RingOrm/'
languageCode = 'en-us'
title = 'Ringormeland'
[params]
  subtitle = 'Alle ringormende'
  [params.contact]
    email = 'info@example.org'
    phone = '+1 202-555-1212'

